services:
  web:
    build: ./app
    ports:
      - 3000:3000
    depends_on:
      - db
  
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
