version: '3'
services:
  webserver:
    image: nginx
    ports: 
      - "${NGINX_PORT}:80"
    environment:
      - NGINX_PORT=${NGINX_PORT}

  db:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes: 
      - db_data:/var/lib/postgressql/data
volumes:
  db_data:
